# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
    adapter: mysql
    database: mra_development
    username: root
    password: pop123
    host: localhost	
test:
    adapter: mysql
    database: mra_test
    username: root
    password: pop123
    host: localhost
production:
    adapter: mysql
    database: mra_production
    username: root
    password: pop123
    host: localhost