# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0350f5ac6fc80714e4df9101e186a76adf43977e950280cae7970d02a87e3218af1bb849885c01df011e8ca68f7a596bd67b0a703d93a820bf5906de2de37a60

test:
  secret_key_base: 3b45e1e95bfb6cd53294aba8f4546fb325e732d75c514fedea537852ab6e6cc2b39f11f3428eb68ffee82c4bfe82f4e9991d4ae0249f694d7ca9ec646c9115a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
